#!/bin/sh
. ts

user_dir="$(pwd)"
export PATH="$user_dir/bin:$PATH"

setup () {
  mkdir -p "$test_dir"
  cd "$test_dir"
  git init
  export GIT_AUTHOR_NAME="John Doe"
  export GIT_AUTHOR_EMAIL="john.doe@example.com"
  export GIT_AUTHOR_DATE="2010-09-08T07:06:05-04:00"
}

teardown () {
  cd "$user_dir"
}

test_write_creates_commit_from_stdin  () {
  sha=`printf "Hello world." | gitgo-write`
  assert_status 0 $?

  git log -n1 $sha | assert_output "\
commit $sha
Author: John Doe <john.doe@example.com>
Date:   Wed Sep 8 07:06:05 2010 -0400

    Hello world.\
" -

  git ls-tree $sha | assert_output "" -
}

test_write_stores_attachments_in_tree  () {
  printf "content\n" > file

  sha=$(printf "Hello world." | gitgo-write -a file)
  assert_status 0 $?

  git ls-tree $sha | assert_output "\
100644 blob d95f3ad14dee633a758d2e331151e950dd13e4ed	file\
" -
}

test_write_accepts_filenames_with_spaces  () {
  printf "content\n" > "filename with spaces"

  sha=$(printf "Hello world." | gitgo-write -a "filename with spaces")
  assert_status 0 $?

  git ls-tree $sha | assert_output "\
100644 blob d95f3ad14dee633a758d2e331151e950dd13e4ed	filename with spaces\
" -
}
