#!/bin/sh
. ts

user_dir="$(pwd)"
export PATH="$user_dir/bin:$PATH"

setup () {
  mkdir -p "$test_dir"
  cd "$test_dir"
}

teardown () {
  cd "$user_dir"
}

use () {
  # git clone errors with bad file descriptor when stdin is closed
  echo | git clone -b gitgo "$user_dir/test/fixtures/$1.git" . > /dev/null
  git fast-export --no-data --export-marks=export_marks gitgo > export_file
}

#
# preview
#

test_preview_option_prints_import () {
  use 'abc'
  gitgo-import
}
