#!/bin/sh
. ts
. test/env

setup () {
  mkdir -p "$test_dir"
  cd "$test_dir"
}

teardown () {
  cd "$user_dir"
}

use () {
  # git clone errors with bad file descriptor when stdin is closed
  echo | git clone -b gitgo "$user_dir/test/fixtures/$1.git" . > /dev/null
  git fast-export --no-data --export-marks=export_marks gitgo > export_file
}

#
# basic
#

test_export_prints_deconvoluted_export_data () {
  use 'abc'
  gitgo-export | assert_output "\
commit refs/namespaces/gitgo/heads/1d46e67766042c5944705377eaf0db511e7b2caf
mark :1
author John Doe <john.doe@example.com> 1283943965 -0400
committer John Doe <john.doe@example.com> 1283943965 -0400
data 2
A

commit refs/namespaces/gitgo/heads/1d46e67766042c5944705377eaf0db511e7b2caf
mark :2
author John Doe <john.doe@example.com> 1283943965 -0400
committer John Doe <john.doe@example.com> 1283943965 -0400
data 2
B
from :1

commit refs/namespaces/gitgo/heads/1d46e67766042c5944705377eaf0db511e7b2caf
mark :3
author John Doe <john.doe@example.com> 1283943965 -0400
committer John Doe <john.doe@example.com> 1283943965 -0400
data 2
C
from :2

" -
}
