#!/bin/sh
. ts
. test/env

setup () {
  mkdir -p "$test_dir"
  cd "$test_dir"
  git init
}

teardown () {
  cd "$user_dir"
}

#
# gitgo_meta
#

test_gitgo_meta_prints_dot_pairs_for_messages () {
a=`printf "A" | gitgo-write`
b=`printf "B" | gitgo-write`
c=`printf "C" | gitgo-write`

gitgo-meta $c | assert_output "\
$c . $c
$b . $b
$a . $a
" -
}

test_gitgo_meta_prints_data_until_second_sha () {
a=`printf "A" | gitgo-write`
b=`printf "B" | gitgo-write`
c=`printf "C" | gitgo-write`

gitgo-meta $c $b | assert_output "\
$c . $c
" -
}

test_gitgo_meta_prints_graph_relations () {
a=`printf "A" | gitgo-write`
b=`printf "B" | gitgo-write $a`
c=`printf "C" | gitgo-write $a $b`

gitgo-meta $c | assert_output "\
$c + $b
$c + $a
$c . $c
$b + $a
$b . $b
$a . $a
" -
}

test_gitgo_meta_prints_tag_data () {
a=`printf "A" | gitgo-write -t one -t two`
b=`printf "B" | gitgo-write -t three`

gitgo-meta $b | assert_output "\
$b : three
$b . $b
$a : two
$a : one
$a . $a
" -
}

test_gitgo_meta_skips_commits_without_metadata () {
a=`printf "A" | gitgo-write`

tree=`git mktree <&-`
sha=`printf "message" | git commit-tree $tree -p $a`
printf "%s\n" "$sha"  > $test_dir/.git/refs/heads/gitgo

b=`printf "B" | gitgo-write $a`

gitgo-meta $b | assert_output "\
$b + $a
$b . $b
$a . $a
" -

git log --oneline gitgo | wc -l | tr -d " \n" | assert_output "3" -
}

test_gitgo_meta_skips_metadata_format_in_middle_of_message () {
a=`printf "A" | gitgo-write`
b=`printf "B
---
+ 0123456789012345678901234567890123456789
+ abcdefabcdefabcdefabcdefabcdefabcdefabcd
+ 0123456789abcdef0123456789abcdef01234567
" | gitgo-write $a`

gitgo-meta $b | assert_output "\
$b + $a
$b . $b
$a . $a
" -
}

#
# -t option
#

test_t_option_lists_relations_in_tsort_order () {
a=`printf "A" | gitgo-write`
b=`printf "B" | gitgo-write $a`
c=`printf "C" | gitgo-write $a $b`

gitgo-meta -t $c | assert_output "\
$a
$b
$c
" -
}