#!/bin/sh

user_dir="$(pwd)"
export PATH="$user_dir/bin:$PATH"
export GIT_DIR="$user_dir/test/fixtures/abc.git"

rm -rf "$GIT_DIR"
mkdir -p "$(dirname "$GIT_DIR")"
git init > /dev/null

a=$(printf "A" | gitgo-write)
b=$(printf "B" | gitgo-write "$a")
c=$(printf "C" | gitgo-write "$b")

git log gitgo
