#!/bin/bash
############################################################################
progname="${0##*/}"
author="Simon Chiang"
usage="usage: %s [-h] GROUP [TARGET_DIR]\n"
opt="       %s   %s\n"

while getopts "h" option
do
  case $option in
    h  )  printf "$usage" "$progname"
          printf '
  Fetch an mbox of messages from gmane.  Reads ranges from stdin which
  should be in the format "START STOP" (STOP is not included). Use this
  pipelind for quick results.

    ./download gmane.comp.version-control.git 0 1 2 |
    ./parse |
    sed -ne 's/[^0-9]*\([0-9]\{1,\}\).*/\1/p' |
    sort -n |
    ./rangeify -e |
    ./fetch gmane.comp.version-control.git

'
          printf "options:\n\n"
          printf "$opt" "-h" "prints this help"
          printf "\n"
          exit 0 ;;
    \? )  printf "$usage" "$progname"
          exit 2 ;;
  esac
done
shift $(($OPTIND - 1))

group="${1}"
target_dir="${2:-$(pwd)}"
if ! [ "$group" ]
then
  printf "no group specified\n"
  exit 1
fi
shift 2

############################################################################

mkdir -p "$target_dir"
while read start stop
do 
  mbox="$target_dir/${start}_${stop}.mbox"
  curl -s "http://download.gmane.org/$group/$start/$stop" > "$mbox"
  index=1
  while [ $start -lt $stop ]
  do
    echo "save $index $target_dir/$start"
    start=$((start + 1))
    index=$((index + 1))
  done | 
  mail -Nf "$mbox"
done
