#!/bin/bash
############################################################################
usage="\
usage: fetch-messages [-h] GROUP [TARGET_DIR]

  Fetch an mbox of messages from gmane. Reads ranges from stdin which should
  be in the format 'START STOP' (STOP is included). Use this pipeline for
  example:

    ./fetch-news gmane.comp.version-control.git 0 1 2 |
    ./parse-news -r |
    ./fetch-messages gmane.comp.version-control.git

  Specify the directory to recieve the messages with TARGET_DIR, which is by
  default working directory.

options:

        -h    prints this help

"
############################################################################

while getopts "h" option
do
  case $option in
    h  )  printf "$usage"
          exit 0 ;;
    \? )  printf "$usage" | head -n 1
          exit 2 ;;
  esac
done
shift $(($OPTIND - 1))

group="${1}"
target_dir="${2:-$(pwd)}"
if ! [ "$group" ]
then
  printf "no group specified\n"
  exit 1
fi
shift 2

############################################################################

mkdir -p "$target_dir"
while read start stop
do 
  mbox="$target_dir/${start}_${stop}.mbox"
  curl -s "http://download.gmane.org/$group/$start/$((stop + 1))" > "$mbox"
  for (( index=$start; index<=$stop; index++ ))
  do echo "save $((index - start + 1)) $target_dir/$index"
  done | 
  mail -Nf "$mbox"
done
