#!/bin/bash
############################################################################
usage="\
usage: parse-news [-a] [-h] [FILE...]

  Fetch an mbox of messages from gmane. Reads ranges from stdin which should
  be in the format 'START STOP' (STOP is not included). Use this pipelind for
  quick results.

    ./download gmane.comp.version-control.git 0 1 2 |
    ./parse |
    sed -ne 's/[^0-9]*\([0-9]\{1,\}\).*/\1/p' |
    sort -n |
    ./rangeify -e |
    ./fetch gmane.comp.version-control.git

options:

        -h    prints this help

"
############################################################################

while getopts "h" option
do
  case $option in
    h  )  printf "$usage"
          exit 0 ;;
    \? )  printf "$usage" | head -n 1
          exit 2 ;;
  esac
done
shift $(($OPTIND - 1))

group="${1}"
target_dir="${2:-$(pwd)}"
if ! [ "$group" ]
then
  printf "no group specified\n"
  exit 1
fi
shift 2

############################################################################

mkdir -p "$target_dir"
while read start stop
do 
  mbox="$target_dir/${start}_${stop}.mbox"
  curl -s "http://download.gmane.org/$group/$start/$stop" > "$mbox"
  index=1
  while [ $start -lt $stop ]
  do
    echo "save $index $target_dir/$start"
    start=$((start + 1))
    index=$((index + 1))
  done | 
  mail -Nf "$mbox"
done
